### ISSUE TITLE
Check Platform Serial Numbers of the Platform Certificate Chain

### ISSUE THREAD

**Issue by iadgovuser26** [nsacyber/HIRS#110]
Section 2.2.6.12 of the Platform Credential Profile states "The Platform Serial Number of the delta must be equal to the  that of the base Platform Certificate or base Delta Platform Certificate." This implies that all Platform certificate serial numbers of a Platform Certificate chain must be equal. Any Platform serial number that does not match will cause the chain to be invalid and any validation of a device associated with the Platform Certificate chain to fail.

**Comment by busaboy1340** [comment]
This ticket will be piggy-backing off of #108 (Create a Validity Check method for Platform Certs)
After initial code look through:

- Validation of Platform serial numbers in the Delta Certificate Chain:
    Could be added to the SupplyChainCredentialValidator.validatePlatformCredential() method.

- Check for any invalid devices associated with the Platform Certificate:
    Reuse/Add-to methods in SupplyChainCredentialValidator.validatePlatformCredentialAttributes()
    to determine device validity.

**Comment by cyrus-dev** [comment]
After reviewing, a check for this was entered into the code for issue #109. The validateDeltaPlatformCredentialAttributes method of the SupplyChainCredentialValidator class compares the base certificate's platform serial to the delta certificate's platform serial.  The only change I could see making, that would help with identifying the problem, is changing the error output to list the serial number of the delta cert, rather than the platform serial number that didn't match.
