### ISSUE TITLE
Fix DeviceInfoCollector to Handle C-Style Strings

### ISSUE THREAD

**Issue by apldev3** [nsacyber/HIRS#135]
The `DeviceInfoCollector` works properly in all instances except for when any of the version tokens happens to end in a C-Style null character. This can happen in certain rare instances depending on the `tpm_version` utility installed on the system.

The fix is simply to trim the version tokens before attempting to parse them as `short`s.

**Comment by apldev4** [comment]
The bug is actually in `tpm_version.cpp`. The `UINT32` contains the following 4 bytes: `\00.2`. When it is placed in the C++ string, the `std::string` adds a `\0` making it `\00.2\0`. When the bytes of the string are reversed, all the characters are reversed except for the null terminator, resulting in `2.0\0\0`. If this were a C-string and `printf` were used, everything would have worked because C determines the string length by how many characters precede the first null character. In that case, no null characters would have been printed. However, the `std::string` in C++ keeps a separate field for the string length and doesn't check to make sure the string does not contain null bytes other than the one it places at the end. When `cout` was being called, the `\0` in the string was being printed (not the null terminator, but the null before that). The solution is to remove any nulls that are in the string  before passing it along (not including the null terminator managed by `std::string`). See #137.

The Java equivalent of this bad behavior would look like this (although no one would ever do this):
```
System.out.print("2.0\0");
```

**Comment by apldev3** [comment]
@apldev4 while I agree the issue was caused by an error in `tpm_version.cpp`, the `DeviceInfoCollector` should have been able to handle that case since we're expecting raw input from a shell command that could provide anything. In this case it left a null in place, and was thus a "C-style" string. Not a C++ `std::string`.
