### ISSUE TITLE
Provide TCG Event Log details associated with a PCR mismatches

### ISSUE THREAD

**Issue by iadgovuser26** [nsacyber/HIRS#238]
Issue #222 added processing of the TCG Event Log and provided the ability to create a set of expected PCRs from the Support RIM file.
Issue #236 adds the ability to process a TPM Quote and determine if a PCR value doesnt match an expected value.

What's needed is some human readable details that help explain what a  PCR mismatch implies (stating PCR 4 failed doesn't mean much to most humans).

To support this feature an ability to compare the Event Log from the Provisioner against the Event Log supplied as a Support RIM file for a given PCR is required . The Event Log comparison will provide details about why the PCRs did not match.

The return value of this method will be a string array containing one human readable entry for each event associated with the specific PCR  that had digests that mismatched. The human readable string is based upon the details provided by a particular Event (the Event Content field), in which the information may be very limiting (typically based upon UEFI structures), but still more information that just a PCR number.

**Comment by cyrus-dev** [comment]
At the moment this is being broken into at least 2 to 3 tasks/PRs.  This is to reduce the number of files changed in one PR and to establish goals to hit before moving on to a different objective necessary to complete the issue.
Task 1 - Collect the locally stored files on the provisioner, the rim and swidtag files.  While this issue is specifically about the rim file, the swidtag is just as easy to include.  The processing of the swidtag will be saved for later.

Task 2 - The next step will be to compare the client rim with the uploaded rim during a failure and find the mis-match.

Task 3 - If necessary, this will be to display this information which will depend on the type of information from the compare is requested to display.
