### ISSUE TITLE
SELinux Policy Issues with HIRS ACA on CentOS 7

### ISSUE THREAD

**Issue by m-morrone** [nsacyber/HIRS#28]
After installing ACA on a CentOS 7 system, navigating to the ACA Portal URL (https://<ACAserveraddress>:8443/HIRS_AttestationCAPortal/) displayed a blank page.  Looking in the tomcat logs, shows:
`192.168.103.1 - - [16/Oct/2018:19:04:20 +0000] "GET /HIRS_AttestationCAPortal HTTP/1.1" 404 -`
SELinux was blocking the connection from tomcat to mysqld, indicated in the audit logs by: `node=server22.simp.test type=AVC msg=audit(1539714234.510:4782): avc:  denied  { name_connect } for  pid=12058 comm="java" dest=3306 scontext=system_u:system_r:tomcat_t:s0 tcontext=system_u:object_r:mysqld_port_t:s0 tclass=tcp_socket`
Could you add a SELinux policy to the RPM to enable this out of the box?

**Comment by apldev4** [comment]
The AttestationCA RPM contains the SELinux policy to fix this very issue. After installing the RPM, look for `/opt/hirs/extras/aca/tomcat-mysql-hirs.pp`. The loading of an SELinux policy by an RPM post-install script may not go over well with System Administrators who want to know what SELinux policies are being run, so the loading of the provided policy has been left to the System Administrator. Simply run the following command as root:
```
semodule -i /opt/hirs/extras/aca/tomcat-mysql-hirs.pp
```
You will need to make sure you have installed the `policycoreutils` package in order to have `semodule`.

**Comment by m-morrone** [comment]
I couldn't find this documented.  Could you add it to the wiki at https://github.com/nsacyber/HIRS/wiki/aca_debug#no-attestation-portal-appears-at-hirs_server-package-portal-url?  Thanks.

**Comment by iadgovuser26** [comment]
Agreed. This should probably be a note on the installation_notes page. It will, however, take a few days to update the pages.

**Comment by trevor-vaughan** [comment]
@apldev1 I would recommend having the RPM compile the policy from scratch like we do over in https://github.com/simp/simp-environment-skeleton/tree/master/build.

As a user, I expect that things are just dropped into place. However, I would be just as uncomfortable running a randomly compiled policy file as I would having the RPM do it. I think having the source components available would make things a lot easier all around.

**Comment by trevor-vaughan** [comment]
Actually, thinking about this a bit more, you could also have a sub-RPM that is just the SELinux bits. That would make me, as a user, have the best experience. I mean, honestly, I would want it to "just work", but I see your point about not mucking about on a system depending on exactly what the policy is doing.

**Comment by apldev4** [comment]
> As a user, I expect that things are just dropped into place. However, I would be just as uncomfortable running a randomly compiled policy file as I would having the RPM do it. I think having the source components available would make things a lot easier all around.

That's a good point. At least providing the pp file and requiring the System Administrators to type the command to add the policy makes them aware that they are responsible for the change that they are making. I agree, though, that providing the Type Enforcement file is even better since it is human-readable.

I'm not sure what you mean by *sub-RPM*, but what about providing the te file instead of the pp file and putting a README file in the directory showing the steps and packages required to compile and add the module to the policy?

**Comment by trevor-vaughan** [comment]
You have have RPM spec files that generate one RPM.

I would expect something like the following RPMs:

* hirs
* hirs-selinux-policy

That said, you're not actually providing these RPMs so you could also just add an environment variable that can be triggered to allow users to build in the auto-policy stuff if they want to and the builder can decide if they want it to happen automatically or not.

I can't think of a time in the recent past when I haven't expected an RPM to do what it was supposed to to allow my application to run if I'm using SELinux. Particularly a security-related app.

I would want the source SELinux files though because otherwise it's as mysterious as doing it automatically.

**Comment by apldev4** [comment]
> I can't think of a time in the recent past when I haven't expected an RPM to do what it was supposed to to allow my application to run if I'm using SELinux. 

This issue is really a result of CentOS7's targeted policy not allowing Tomcat to use the default port of MySQL -- regardless of the webapp being run. I expect that eventually, there will be an updated version of the `selinux-policy-targeted` package in CentOS7 that fixes this problem.

If you want, we can just load the policy package file from the post-install script in the meantime. 

Thanks for helping me think this through some more.

**Comment by trevor-vaughan** [comment]
I'd be thrilled with a `%post` like we have in the `simp-environment-skeleton` spec file.

It follows the suggestions as made by the Fedora project should should allow for inclusion in EPEL if you ever want to go that route.

**Comment by m-morrone** [comment]
Yes, thanks.
