### ISSUE TITLE
PlatformSerial optional field in Subject Alternative Name

### ISSUE THREAD

**Issue by iadgovuser29** [nsacyber/HIRS#72]
PlatformSerial is defined as an optional value in the Subject Alternative Name.  Most platforms should have the information that goes into this value available.  If they don't, then the platform certificate might not include the value.  

Field Name | RFC 5280 Type | Value | Field Status
------------ | ------------ | ------------ | ------------ 
| Subject Alternative Name | GeneralName<br/>directoryName | PlatformManufacturerStr<br/>PlatformModel<br/>PlatformVersion<br/>PlatformSerial (optional)<br/>PlatformManufacturerId (optional) | MUST<br/>critical/non-critical<br/>(depending on subject) |

The specification says:
> During certificate validation, the Privacy-CA MUST check that the platform manufacturer, model, version, serial numbers, and manufacturer ID are acceptable.

Currently, if the ACA finds that the value is not present in the certificate, then it throw a null error.

Since the value is optional, the appraisal should fail only if the value is not the same in the device info and the certificate.  If neither have a platform serial number, appraisal should continue.

**Comment by cyrus-dev** [comment]
The IllegalStateException error on a null object is separate from the fail associated with this issue.  But I've taken a bit of time to get this set up and tested.  I've used a docker container of the provisioner against a VM ACA.  The error is gone but I'm still getting a fail because the values being compared from the emulator is null -> "somevalue" for the system serial number and null -> "Not Specified" for the base board serial number.
